name: Pylint + tests

on: [push]

env:
  python-version: '3.10'
  POSTGRES_DB: testdb
  POSTGRES_HOST: '127.0.0.1'
  POSTGRES_PORT: 5432
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  REDIS_HOST: '127.0.0.1'

jobs:
  run-tests:
    services:
      db:
        image: postgres:14.1-alpine
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_HOST: ${{env.POSTGRES_HOST}}
          POSTGRES_PORT: ${{env.POSTGRES_PORT}}
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - '5432:5432'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.python-version }}
    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: run-tests
      working-directory: backend
      run: |
        poetry run python manage.py makemigrations
        poetry run coverage run --source='.' manage.py test -v 3 --parallel auto
    - name: coverage-report
      working-directory: backend
      run: |
        poetry run coverage report
    - name: pep-test
      working-directory: backend
      run: |
        poetry run pylint -j 0 .